# Generated by Django 4.0.6 on 2022-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category_code',
            field=models.CharField(max_length=30, verbose_name='Код категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category_name',
            field=models.CharField(max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_code',
            field=models.CharField(max_length=30, verbose_name='Код подкатегории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory_name',
            field=models.CharField(max_length=30, verbose_name='Название подкатегории'),
        ),
    ]
